DROP DATABASE IF EXISTS COURSEPLANNER;

CREATE DATABASE COURSEPLANNER;

USE COURSEPLANNER;

CREATE TABLE USER (
	USERID INT(11) AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	FNAME VARCHAR(255),
	LNAME VARCHAR(255),
	EMAIL VARCHAR(255)
);

create table application(
	post varchar(50),
	applicant varchar(50),
	submitted_on varchar(20)
);
create table position(
	post varchar(50)
);

INSERT INTO USER (USERNAME,PASSWORD,FNAME,LNAME,EMAIL) VALUES
	('vatsal','4444','Vatsal','Sevak','vatsalsevak.2010@gmail.com');
	
INSERT INTO USER (USERNAME,PASSWORD,FNAME,LNAME,EMAIL) VALUES
	('vats1989','1234','Vatsal','Sevak','vatsalsevak_2010@gmail.com');	

CREATE TABLE COURSE	(
	COURSEID INT(11) AUTO_INCREMENT PRIMARY KEY,
	CODE VARCHAR(10) UNIQUE NOT NULL,
	TITLE VARCHAR(255) NOT NULL
);
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS120','Introduction to Web Site Development');
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS122','Using Relational Databases and SQL');
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS201','Introduction to Programming');
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS202','Introduction to Object Oriented Programming');
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS203','Programming with Data Structures');
INSERT INTO COURSE(CODE, TITLE) VALUES ('CS320','Web and Internet Programming');

CREATE TABLE QUARTER (
	QUARTERID INT(11) AUTO_INCREMENT PRIMARY KEY,
	SEASON VARCHAR(10) NOT NULL,
	YEAR INT(4) NOT NULL
);
INSERT INTO QUARTER (SEASON, YEAR) VALUES
	('Fall',2014),('Winter',2015),('Spring',2015),('Summer',2015);

CREATE TABLE COURSEOFFERING	(
	COURSEOFFERINGID INT(11) AUTO_INCREMENT PRIMARY KEY,
	COURSEID INT(11) NOT NULL,
	QUARTERID INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID),
	CONSTRAINT FOREIGN KEY (QUARTERID) REFERENCES QUARTER(QUARTERID)
);
INSERT INTO COURSEOFFERING(COURSEID,QUARTERID) VALUES
	(1,1),(2,1),(3,1),(4,1),(5,1);
INSERT INTO COURSEOFFERING(COURSEID,QUARTERID) VALUES
	(5,2),(6,2);

CREATE TABLE PREREQUISITES (
	PREREQUISITESID INT(11) AUTO_INCREMENT PRIMARY KEY,
	COURSEID INT(11) NOT NULL,
	PRECOURSEID INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID),
	CONSTRAINT FOREIGN KEY (PRECOURSEID) REFERENCES COURSE(COURSEID)
);
INSERT INTO PREREQUISITES(COURSEID,PRECOURSEID) VALUES
	(4,3),(5,4),(6,1),(6,2),(6,5);
	
	320,120
	320,122
	320,203


CREATE TABLE REGISTEREDCOURSES (
	REGISTEREDCOURSESID INT(11) AUTO_INCREMENT PRIMARY KEY,
	USERID INT(11) NOT NULL,
	COURSEOFFERINGID INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY(USERID) REFERENCES USER(USERID),
	CONSTRAINT FOREIGN KEY(COURSEOFFERINGID) REFERENCES COURSEOFFERING(COURSEOFFERINGID)
);

SELECT C1.CODE,C1.TITLE
FROM COURSE C, COURSE C1, PREREQUISITES P
WHERE C.COURSEID = P.COURSEID
AND C1.COURSEID = P.PRECOURSEID
AND C.CODE = 'CS320';